name: Deploy to Kubernetes

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config

      # - name: Deploy (apply manifests)
      #   run: |
      #     IMAGE="ghcr.io/${{ github.repository }}:${{ github.sha }}"
      #     sed -i.bak "s|REPLACE_AT_DEPLOY_TIME|${{ github.sha }}|g" k8s/deployment.yaml
      #     kubectl apply -f k8s/

      - name: Deploy (apply manifests)
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${{ github.sha }}"
          sed -i.bak "s|image:.*|image: ${IMAGE}|g" k8s/deployment.yaml
          kubectl apply -f k8s/
