name: Deploy to Kubernetes

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Fetch kubeconfig from DigitalOcean
        run: |
          doctl kubernetes cluster kubeconfig save 0626509a-4e15-4f0c-8fdb-84899327af85
          kubectl get nodes

      - name: Deploy (apply manifests)
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${{ github.sha }}"
          sed -i.bak "s|image:.*|image: ${IMAGE}|g" k8s/deployment.yaml
          kubectl apply -f k8s/
